---

consul_group_name: "{{ lookup('env','CONSUL_GROUP_NAME') | default('consul_instances', true) }}"
consul_servers: "\
  {% set _consul_servers = [] %}\
  {% for host in groups[consul_group_name] %}\
    {% set _consul_node_role = hostvars[host]['consul_node_role'] | default('client', true) %}\
    {% if ( _consul_node_role == 'server' or _consul_node_role == 'bootstrap') %}\
      {% if _consul_servers.append(host) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ _consul_servers }}"

main_inventory_group: "{{ lookup('env','HOSTS_GROUP_NAME') | default('all', true) }}"
inventory_servers: "\
  {% set _inventory_servers = [] %}\
  {% for host in groups[main_inventory_group] %}\
    {% if _inventory_servers.append(host) %}{% endif %}\
  {% endfor %}\
  {{ _inventory_servers }}"

bind_ipv4: "{{ isc_bind_ipv4 | default(true, true) }}"
bind_ipv6: "{{ isc_bind_ipv6  | default(false, true) }}"

_consul_lan_servers: "\
  {% set __consul_lan_servers = [] %}\
  {% for server in consul_servers %}\
    {% set _consul_datacenter = hostvars[server]['consul_datacenter'] | default('dc1', true) %}\
    {% if _consul_datacenter == consul_datacenter %}\
      {% if ansible_system == 'FreeBSD' %}\
        {% set __host_ip = lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[server]['ansible_'+ consul_iface ]['ipv4'][0]['address'], true) %}\
      {% elif ansible_os_family == 'Windows'  %}\
        {% set __host_ip = lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[server]['ansible_ip_addresses'][0], true) %}\
      {% else %}\
        {% set __host_ip = lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[server]['ansible_'+ consul_iface | replace('-', '_')]['ipv4']['address'], true) %}\
      {% endif %}\
      {% set __host_name = hostvars[server]['inventory_hostname'] %}\
      {% if __consul_lan_servers.append({'name': __host_name, 'ip': __host_ip}) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ __consul_lan_servers }}"

_consul_wan_servers: "\
  {% set __consul_wan_servers = [] %}\
  {% for server in consul_servers %}\
    {% set _consul_datacenter = hostvars[server]['consul_datacenter'] | default('dc1', true) %}\
    {% if _consul_datacenter != consul_datacenter %}\
      {% if ansible_system == 'FreeBSD' %}\
        {% set __host_ip = lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[server]['ansible_'+ consul_iface ]['ipv4'][0]['address'], true) %}\
      {% elif ansible_os_family == 'Windows'  %}\
        {% set __host_ip = lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[server]['ansible_ip_addresses'][0], true) %}\
      {% else %}\
        {% set __host_ip = lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[server]['ansible_'+ consul_iface | replace('-', '_')]['ipv4']['address'], true) %}\
      {% endif %}\
      {% set __host_name = hostvars[server]['inventory_hostname'] %}\
      {% if __consul_wan_servers.append({'name': __host_name, 'ip': __host_ip}) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ __consul_wan_servers }}"

_ansible_hosts: "\
   {% set __ansible_hosts = [] %}\
   {% for host in inventory_servers %}\
     {% set _public_iface = hostvars[host]['public_iface'] %}\
     {% if ansible_system == 'FreeBSD' %}\
       {% set __host_ip = lookup('env','HCNP_NODE_EXTERNAL_IP') | default(hostvars[host]['ansible_'+ _public_iface ]['ipv4'][0]['address'], true) %}\
     {% elif ansible_os_family == 'Windows'  %}\
       {% set __host_ip = lookup('env','HCNP_NODE_EXTERNAL_IP') | default(hostvars[host]['ansible_ip_addresses'][0], true) %}\
     {% else %}\
       {% set __host_ip = lookup('env','HCNP_NODE_EXTERNAL_IP') | default(hostvars[host]['ansible_'+ _public_iface | replace('-', '_')]['ipv4']['address'], true) %}\
     {% endif %}\
     {% set __host_name = hostvars[host]['inventory_hostname'] %}\
     {% if __ansible_hosts.append({'name': __host_name, 'ip': __host_ip}) %}{% endif %}\
   {% endfor %}\
   {{ __ansible_hosts }}"

bind_acls: "{{ isc_bind_acls }}"
master_server: "{{ _dns_master_address }}"
bind_forwarders: "{{ _consul_wan_servers + isc_bind_forwarders }}"
domain:
  name: "{{ _dns_domain }}"
  networks: "{{ isc_bind_domain.networks }}"
  dns_servers: "{{ _consul_lan_servers }}"
  hosts: "{{ _ansible_hosts }}"

