---

# Authoritative DNS IP address
_dns_master_address: "{{ isc_bind_master_server | default({ 'name': 'gateway-node', 'ip': '172.16.1.254' }, true) }}"
# Authoritative DNS domain
_dns_domain: "{{ isc_bind_domain.name | default('consul', true) }}"
