---

- name: Gather facts from ALL hosts (regardless of limit or tags)
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  when: hostvars[item]['ansible_default_ipv4'] is not defined
  with_items: "{{ groups['all'] }}"

# src: http://derpturkey.com/setting-host-with-ansible-in-ubuntu/
- name: Update hostname in /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1    {{ inventory_hostname }}'
    state: present

# src: https://gist.github.com/rothgar/8793800
- name: "Build hosts file"
  become: yes
  blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars[item]['ansible_' + hostvars[item]['public_iface']]['ipv4']['address'] }} {{ item }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    state: present
    backup: yes
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all']|flatten(levels=1) }}"
#
#  lineinfile:
#    path: /etc/hosts
#    regexp: '.*{{ item }}$'
#    line: "{{ hostvars[item]['ansible_' + hostvars[item]['public_iface']]['ipv4']['address'] }} {{item}}"
#    state: present
#    backup: yes
#  when: hostvars[item].ansible_default_ipv4.address is defined
#  loop: "{{ groups['all']|flatten(levels=1) }}"
