---

- name: Install and configure Traefik
  become: true
  import_role:
    name: kibatic.traefik
  tags:
    - traefik

- name: Register Traefik dashboard service with Consul
  consul:
    service_name: "traefik-dashboard"
    service_port: "8081"
    host: "{{ consul_host }}"
    tags:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:{{ traefik_address }};PathPrefix:/;"
  delegate_to: "{{ ansible_controller }}"

- name: Register Consul dashboard service with Consul
  consul:
    service_name: "consul-dashboard"
    service_port: "8500"
    host: "{{ consul_host }}"
    tags:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:{{ traefik_address }};PathPrefix:/consul;ReplacePathRegex: ^/consul/(.*) /$1"
      - "traefik.frontend.redirect.replacement='$1/consul/'"
      - "traefik.frontend.redirect.regex='^(.*)/consul$'"
  delegate_to: "{{ ansible_controller }}"

- name: Register Nomad dashboard service with Consul
  consul:
    service_name: "nomad-dashboard"
    service_port: "4646"
    host: "{{ consul_host }}"
    tags:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:{{ traefik_address }};PathPrefix:/nomad;ReplacePathRegex: ^/nomad/(.*) /$1"
      - "traefik.frontend.redirect.replacement='$1/nomad/'"
      - "traefik.frontend.redirect.regex='^(.*)/nomad$'"
  delegate_to: "{{ ansible_controller }}"
