---

- name: Gather facts from ALL hosts (regardless of limit or tags)
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  when: hostvars[item]['ansible_default_ipv4'] is not defined
  with_items: "{{ groups['all'] }}"

- name: Generate Bind configuration file
  template:
    src: config.yml.j2
    dest: "{{ playbook_dir }}/roles/dns/vars/config.yml"
  delegate_to: ansible-node.consul

- name: Include generated Bind vars
  include_vars:
    dir: vars
    files_matching: config.yml

- name: Install and configure ISC Bind
  become: true
  import_role:
    name: isc.bind
  tags:
    - dns

- name: Configure DNS name server in network interfaces configuration
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{ dns_iface }}"
    option: dns-search
    value: "{{ domain.name }}"
    backup: yes
    state: present

- name: Configure DNS search network interfaces configuration
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{ dns_iface }}"
    option: dns-nameservers
    value: "{{ master_server.ip }}"
    backup: yes
    state: present

# Is there a better way to do this? We are trying to get resolvconf to re-generate the resolv.conf file
- name: Restart network interface
  become: true
  shell: "ifdown {{ dns_iface }} && ifup {{ dns_iface }}"

