---

all:

  hosts:

    localhost:
      ansible_connection: local
      ansible_host: localhost
      ansible_user: philip
      public_iface: wlp3s0
    hcnp-node-0:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-50
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0
    hcnp-node-1:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-53
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0
    hcnp-node-2:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-54
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0
    hcnp-node-3:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-55
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0

  children:
  
    compute_nodes:
      hosts:
        hcnp-node-1:
        hcnp-node-2:
        hcnp-node-3:

    consul_instances:
      hosts:
        hcnp-node-1:
          consul_dnsmasq_enable: true
          consul_node_role: bootstrap
        hcnp-node-2:
          consul_dnsmasq_enable: true
          consul_node_role: server
        hcnp-node-3:
          consul_dnsmasq_enable: true
          consul_node_role: server
      vars:
        # vars required to generate DNS settings, do not move
        consul_acl_datacenter: "hcnp"
        consul_datacenter: hcnp
        consul_dnsmasq_servers: ['192.168.1.254']
        consul_domain: "hcnp"
        consul_iface: eth0
        consul_recursors: ['192.168.1.254']

    controller_instance:
      hosts:
        localhost:

    dns_instances:
      hosts:
        dns-node.consul:
          consul_datacenter: hcnp
          consul_iface: eth0

    docker_instances:
      hosts:
        hcnp-node-1:
        hcnp-node-2:
        hcnp-node-3:

    gateway_instances:
      hosts:
        hcnp-node-0:
          traefik_iface: eth0
          consul_host: 192.168.1.53
          traefik_binary_url: https://github.com/containous/traefik/releases/download/v1.7.14/traefik_linux-arm

    nomad_instances:
      hosts:
        hcnp-node-1:
          nomad_iface: eth0
          nomad_node_role: server
        hcnp-node-2:
          nomad_iface: eth0
          nomad_node_role: client
        hcnp-node-3:
          nomad_iface: eth0
          nomad_node_role: client

    vault_instances:
      hosts:
        hcnp-node-1:
          vault_iface: eth0
          vault_node_role: bootstrap
        hcnp-node-2:
          vault_iface: eth0
          vault_node_role: server
        hcnp-node-3:
          vault_iface: eth0
          vault_node_role: server
