---

all:

  hosts:

    ansible-node:
      ansible_connection: local
      ansible_host: localhost
      ansible_user: philip
      public_iface: wlp3s0
    hcnp-node-0:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-50
      ansible_user: pi
      public_iface: eth0
      cluster_iface: eth0
    hcnp-node-1:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-53
      ansible_user: pi
      public_iface: eth0
      cluster_iface: eth0
    hcnp-node-2:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-54
      ansible_user: pi
      public_iface: eth0
      cluster_iface: eth0
    hcnp-node-3:
      ansible_connection: ssh
      ansible_host: rpi-hcnp-node-55
      ansible_user: pi
      public_iface: eth0
      cluster_iface: eth0

  children:
  
    hcnp_compute_nodes:
      hosts:
        hcnp-node-1:
        hcnp-node-2:
        hcnp-node-3:

    dns_instances:
      hosts:
        dns-node.consul:
          dns_iface: eth0
          consul_datacenter: hcnp
          consul_iface: eth0

    consul_instances:
      hosts:
        hcnp-node-1:
          consul_iface: eth0
          consul_node_role: bootstrap
        hcnp-node-2:
          consul_iface: eth0
          consul_node_role: server
        hcnp-node-3:
          consul_iface: eth0
          consul_node_role: server
      vars:
        consul_dnsmasq_enable: true

    docker_instances:
      hosts:
        hcnp-node-1:
        hcnp-node-2:
        hcnp-node-3:

    gateway_instances:
      hosts:
        hcnp-node-0:
          traefik_iface: eth0
          consul_host: 192.168.1.53
          traefik_binary_url: https://github.com/containous/traefik/releases/download/v1.7.14/traefik_linux-arm

    nomad_instances:
      hosts:
        hcnp-node-1:
          consul_iface: eth0
          consul_node_role: server
        hcnp-node-2:
          consul_iface: eth0
          consul_node_role: client
        hcnp-node-3:
          consul_iface: eth0
          consul_node_role: client

    vault_instances:
      hosts:
        hcnp-node-1:
          consul_iface: eth0
          consul_node_role: bootstrap
        hcnp-node-2:
          consul_iface: eth0
          consul_node_role: server
        hcnp-node-3:
          consul_iface: eth0
          consul_node_role: server
